# Generated by Django 4.1.5 on 2023-01-15 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('rollno', models.CharField(max_length=100)),
                ('hallno', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('club_preference', models.CharField(max_length=300)),
                ('roles_preference', models.CharField(max_length=300)),
                ('answer_1_text', models.TextField(max_length=1000)),
                ('answer_2_text', models.TextField(max_length=1000)),
                ('answer_3_text', models.TextField(max_length=1000)),
            ],
        ),
    ]
