# Generated by Django 4.1.5 on 2023-01-15 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='email',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
