# Generated by Django 3.2.16 on 2023-01-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_candidate_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='answer_4_text',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='answer_5_text',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='answer_6_text',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='answer_7_text',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='answer_8_text',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='answer_9_text',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
